version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql-drugstore-smart
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drugstore_db
      MYSQL_USER: drugstore_user
      MYSQL_PASSWORD: drugstore_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
